import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconHome,
  IconBrandDiscord,
  IconCrown,
  IconShare,
  IconCloud,
  IconFolder,
  IconDeviceGamepad2,
  IconDice,
  IconForms,
  IconMouse,
  IconRefresh,
  IconWheel,
  IconBrandX
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  // New icons for linktree theme
  home: IconHome,
  image: IconPhoto,
  discord: IconBrandDiscord,
  crown: IconCrown,
  share: IconShare,
  cloud: IconCloud,
  folder: IconFolder,
  gamepad: IconDeviceGamepad2,
  spiral: IconUser, // Using user icon as placeholder for spiral
  dice: IconDice,
  form: IconForms,
  gallery: IconPhoto,
  mouse: IconMouse,
  refresh: IconRefresh,
  wheel: IconWheel,
  'brand-x': IconBrandX
};
